server:
  port: 9201
spring:
  cloud:
    gateway:
      routes:
        - id: requestratelimiter_route
          uri: http://localhost:8201/user/{id}
          filters:
            - name: RequestRateLimiter
              args:
                frequency-rate-limiter.period: 5000
                frequency-rate-limiter.times: 2
                key-resolver: "#{@hostKeyResolver}"
          predicates:
            - Path=/user/{id}
            - Method=GET
logging:
  level:
    org.springframework.cloud.gateway: debug
